export const STOMPCURRENTPRICE = 'STOMPCURRENTPRICE';
export const STOCKSYMBOLLIST = 'STOCKSYMBOLLIST';
export const CURSYMBOLINFO = 'CURSYMBOLINFO';
export const USERACCOUNT = 'USERACCOUNT';
export const ISLOGIN = 'ISLOGIN';
export const CHANGETYPE = 'CHANGETYPE';
export const CHANGETEALTOKEN = 'CHANGETEALTOKEN';
export const ISSHOWLOGIN = 'ISSHOWLOGIN';
export const WATCHDATALIMT = 'WATCHDATALIMT';
export const CURRENTORDERLIMT = 'CURRENTORDERLIMT';
export const HISTORYORDERLIMT = 'HISTORYORDERLIMT';
export const ALLOWFOLLOWINGLIMT = 'ALLOWFOLLOWINGLIMT';
export const CACHECURORDERPRIFIT = 'CACHECURORDERPRIFIT';
export const CACHEPROFITS = 'CACHEPROFITS';
export const CHAHESTOMPPRICES = 'CHAHESTOMPPRICES'; // stomp价格缓存

