export const OPTIONLISTDATA = 'OPTIONLISTDATA';
export const STOMPCURRENTPRICE = 'STOMPCURRENTPRICE';
export const STOCKSYMBOLLIST = 'STOCKSYMBOLLIST';
export const INFODATA = 'INFODATA';//没用到
export const CURSYMBOLINFO = 'CURSYMBOLINFO';
export const USERACCOUNT = 'USERACCOUNT';
export const ISLOGIN = 'ISLOGIN';
export const CHANGETYPE = 'CHANGETYPE';
export const WATCHDATALIMT = 'WATCHDATALIMT';
export const CURRENTORDERLIMT = 'CURRENTORDERLIMT';
export const HISTORYORDERLIMT = 'HISTORYORDERLIMT';
export const ALLOWFOLLOWINGLIMT = 'ALLOWFOLLOWINGLIMT';

